# Generated by Django 4.2.4 on 2023-08-26 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="address_line_1",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address_line_2",
        ),
    ]
